In [10]:
import pandas as pd
import numpy as np

data=[1,2,3,4,5]
s=pd.Series(data,index=['A','B','C','D','E'],name="numbers",dtype="float")
print(s)

data=(1,2,3,4,5)
t=pd.Series(data)
print(t)

data={1:"a",2:"B",3:"c",4:"D",5:"E"}
s1=pd.Series(data)
print(s1)

A    1.0
B    2.0
C    3.0
D    4.0
E    5.0
Name: numbers, dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
1    a
2    B
3    c
4    D
5    E
dtype: object

In [14]:
s=pd.Series(5,index=[0,1,2,3,4])
print(s)

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [33]:
s=pd.Series([35,70,85,77,87],index=['A','B','C','D','E'],name="Numbers",dtype="float")
print(s)
print()
print(s.values)
print(s.index)
print(s.shape)
print(s.size)
print(s.ndim)
print(s.hasnans)
print(s.name)
print(s.dtypes)
print(s.is_unique)

A    35.0
B    70.0
C    85.0
D    77.0
E    87.0
Name: Numbers, dtype: float64

[35. 70. 85. 77. 87.]
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
(5,)
5
1
False
Numbers
float64
True

In [65]:
data=[35,70,85,77,87]
s=pd.Series(data,index=['A','B','C','D','E'])
print(s.loc['C'])
print(s.iloc[2])
#print(s.loc[2]) KeyError
#print(s.iloc['C']) TypeError: Cannot index by location index with a non-integer key

print(s.loc['B':'D'])
#print(s.loc[2:4]) TypeError: cannot do slice indexing on Index with these indexers [2] of type int
#print(s.iloc['B':'D']) TypeError: cannot do positional indexing on Index with these indexers [B] of type str
print(s.iloc[2:4])

print(s.iloc[2])
print(s.iloc[4])

85
85
B    70
C    85
D    77
dtype: int64
C    85
D    77
dtype: int64
85
87

In [59]:
data=[35,70,85,77,87]
s=pd.Series(data)
print(s.loc[2])
print(s.iloc[2])
#print(s.loc['C']) KeyError
#print(s.iloc['C']) TypeError: Cannot index by location index with a non-integer key

85
85

 loc[]

1.Access labeled index data
2.inbclude end index position

iloc[]

1.Access integer index
2.Exclude end index position

In [71]:
data=[35,70,85,77,87]
s=pd.Series(data,index=['A','B','C','D','E'])

print(s.iloc[[2,4]])
print(s.loc[['C','E']])

C    85
E    87
dtype: int64
C    85
E    87
dtype: int64

In [91]:
data=[35,70,85,77,87]
s=pd.Series(data,index=['A','B','C','D','E'])
print(s.loc[s>50])

s.loc['C':'E']=75
print(s)

B    70
C    85
D    77
E    87
dtype: int64
A    35
B    70
C    75
D    75
E    75
dtype: int64

In [96]:
data=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(data)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [100]:
data={'A':{'P':1,'Q':1},'B':{'X':3,'Y':4}}
df=pd.DataFrame(data)
print(df)

     A    B
P  1.0  NaN
Q  1.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [101]:
data=[{'A':{'P':1,'Q':1},'B':{'X':3,'Y':4}}]
df=pd.DataFrame(data)
print(df)

                  A                 B
0  {'P': 1, 'Q': 1}  {'X': 3, 'Y': 4}

In [106]:
data={'A':[1,2,3,4],'B':['W','X','Y','Z']}
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df)

   A  B
A  1  W
B  2  X
C  3  Y
D  4  Z

In [27]:
import pandas as pd
import numpy as np
data={'Name':['Dhoni','Rohit','Virat','Gill'],'Run':[12000,10000,3000,4200],'AVG':[59.9,48.7,51.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df)
print()
print(df.shape)
print(df.ndim)
print(df.index)
print(df.columns)

    Name    Run   AVG
A  Dhoni  12000  59.9
B  Rohit  10000  48.7
C  Virat   3000  51.2
D   Gill   4200  45.3

(4, 3)
2
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['Name', 'Run', 'AVG'], dtype='object')
    Name    Run   AVG
A  Dhoni  12000  59.9
B  Rohit  10000  48.7
C  Virat   4000  51.2
D   Gill   4200  45.3

In [4]:
df['Run']

A    12000
B    10000
C     3000
D     4200
Name: Run, dtype: int64

In [9]:
print(df[['Run','AVG']])

     Run   AVG
A  12000  59.9
B  10000  48.7
C   3000  51.2
D   4200  45.3

In [20]:
print(df[1:])
print()
print(df.loc['B':'D'])

    Name    Run   AVG
B  Rohit  10000  48.7
C  Virat   3000  51.2
D   Gill   4200  45.3

    Name    Run   AVG
B  Rohit  10000  48.7
C  Virat   3000  51.2
D   Gill   4200  45.3

In [28]:
df.loc['C','Run']=4000
print(df)

    Name    Run   AVG
A  Dhoni  12000  59.9
B  Rohit  10000  48.7
C  Virat   4000  51.2
D   Gill   4200  45.3

In [34]:
df.set_index('Name',drop=False)

        Name    Run   AVG
Name
Dhoni  Dhoni  12000  59.9
Rohit  Rohit  10000  48.7
Virat  Virat   4000  51.2
Gill    Gill   4200  45.3

In [33]:
df.set_index(['Name','AVG'],drop=True)

              Run
Name  AVG
Dhoni 59.9  12000
Rohit 48.7  10000
Virat 51.2   4000
Gill  45.3   4200

In [35]:
df.reset_index()

  index   Name    Run   AVG
0     A  Dhoni  12000  59.9
1     B  Rohit  10000  48.7
2     C  Virat   4000  51.2
3     D   Gill   4200  45.3

In [37]:
data={'Name':['Dhoni','Rohit','Virat','Gill'],'Run':[12000,10000,3000,4200],'AVG':[59.9,48.7,51.2,45.3]}
data['Score']=[1000,2000,3000,4000] # Add new column 
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df)

    Name    Run   AVG  Score
A  Dhoni  12000  59.9   1000
B  Rohit  10000  48.7   2000
C  Virat   3000  51.2   3000
D   Gill   4200  45.3   4000

In [46]:
df[(df['Run']>1000) & (df['AVG']>50)]

    Name    Run   AVG  Score
A  Dhoni  12000  59.9   1000
C  Virat   3000  51.2   3000

In [53]:
df[['Run','AVG']][(df['Run']>10000) & (df['AVG']>50)]

     Run   AVG
A  12000  59.9

In [56]:
df.sort_values('AVG',ascending=False)

    Name    Run   AVG  Score
A  Dhoni  12000  59.9   1000
C  Virat   3000  51.2   3000
B  Rohit  10000  48.7   2000
D   Gill   4200  45.3   4000

In [61]:
df.sort_values('AVG',ascending=False,axis=0)

    Name    Run   AVG  Score
A  Dhoni  12000  59.9   1000
C  Virat   3000  51.2   3000
B  Rohit  10000  48.7   2000
D   Gill   4200  45.3   4000

In [71]:
df.sort_index(axis=1,ascending=False)

   Score    Run   Name   AVG
A   1000  12000  Dhoni  59.9
B   2000  10000  Rohit  48.7
C   3000   3000  Virat  51.2
D   4000   4200   Gill  45.3

In [79]:
data={'Name':['Dhoni','Rohit','Virat','Gill'],'Run':[12000,3000,3000,4200],'AVG':[59.9,51.7,48.2,45.3]}
df=pd.DataFrame(data,index=['A','B','C','D'])

df.sort_values(['Run','AVG'],axis=0,ascending=[True,False])

    Name    Run   AVG
B  Rohit   3000  51.7
C  Virat   3000  48.2
D   Gill   4200  45.3
A  Dhoni  12000  59.9

In [84]:
df.sort_values(['Run','AVG'],axis=0,ascending=[True,False],ignore_index=True,inplace=False)

    Name    Run   AVG
0  Rohit   3000  51.7
1  Virat   3000  48.2
2   Gill   4200  45.3
3  Dhoni  12000  59.9