In [35]:
import pandas as pd
import numpy as np

df=pd.read_csv("titanic.csv")
print(df)
print()
df.head()

      pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female
1          1                   Allison, Master. Hudson Trevor    male
2          1                     Allison, Miss. Helen Loraine  female
3          1             Allison, Mr. Hudson Joshua Creighton    male
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304       3                             Zabour, Miss. Hileni  female
1305       3                            Zabour, Miss. Thamine  female
1306       3                        Zakarian, Mr. Mapriededer    male
1307       3                              Zakarian, Mr. Ortin    male
1308       3                               Zimmerman, Mr. Leo    male

          age  sibsp  parch  ticket      fare    cabin embarked  survived
0     29.0000      0      0   24160  211.3375       B5        S         1
1      0.9167      1      2  113781  151.5500  C22 C26        S         1
2      2.0000      1      2  113781  151.5500  C22 C26        S         0
3     30.0000      1      2  113781  151.5500  C22 C26        S         0
4     25.0000      1      2  113781  151.5500  C22 C26        S         0
...       ...    ...    ...     ...       ...      ...      ...       ...
1304  14.5000      1      0    2665   14.4542      NaN        C         0
1305      NaN      1      0    2665   14.4542      NaN        C         0
1306  26.5000      0      0    2656    7.2250      NaN        C         0
1307  27.0000      0      0    2670    7.2250      NaN        C         0
1308  29.0000      0      0  315082    7.8750      NaN        S         0

[1309 rows x 11 columns]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [6]:
df.describe()

,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [7]:
df.nunique()

pclass         3
name        1307
sex            2
age           98
sibsp          7
parch          8
ticket       929
fare         281
cabin        186
embarked       3
survived       2
dtype: int64

In [9]:
df.shape

(1309, 11)

In [12]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [20]:
(df['sex']=='male').value_counts()

sex
True     843
False    466
Name: count, dtype: int64

In [28]:
df['sex'].value_counts('male')*100

sex
male      64.400306
female    35.599694
Name: proportion, dtype: float64

In [ ]:
(df['sex']=='male').value_counts()

In [30]:
df.isnull().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [39]:
df['age']=df['age'].fillna(df['age'].mean())
df.isnull().sum()

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin       1014
embarked       2
survived       0
dtype: int64

In [40]:
df['fare']=df['fare'].fillna(df['fare'].median())
df.isnull().sum()

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin       1014
embarked       2
survived       0
dtype: int64

#### object:Mode     and    int,float : Mean,Median

In [44]:
df['embarked']=df['embarked'].fillna(df['embarked'].mode()[0])
df.isnull().sum()

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           0
cabin       1014
embarked       0
survived       0
dtype: int64

In [47]:
df['cabin']=df['cabin'].fillna(method="bfill")
df.isnull().sum()

pclass       0
name         0
sex          0
age          0
sibsp        0
parch        0
ticket       0
fare         0
cabin       59
embarked     0
survived     0
dtype: int64

In [48]:
df['cabin']=df['cabin'].fillna(method="ffill")
df.isnull().sum()

pclass      0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
cabin       0
embarked    0
survived    0
dtype: int64

In [88]:
import pandas as pd
import numpy as np

df=pd.read_csv("titanic.csv")
#print(df)
df.head(10)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0

In [89]:
df.dtypes

pclass        int64
name         object
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
cabin        object
embarked     object
survived      int64
dtype: object

In [90]:
df.isnull().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [91]:
df.shape

(1309, 11)

In [92]:
df=df.dropna(how='all')

In [93]:
df.shape

(1309, 11)

In [85]:
df.drop(columns='age')

,pclass,name,sex,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,0,0,315082,7.8750,NaN,S,0

In [95]:
df.drop(index=[0,2])

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [97]:
df=df.drop("Gender",axis=1,errors="ignore")
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [101]:
df.duplicated().sum()

0

In [102]:
df.duplicated(subset="age",keep="first")

0       False
1       False
2       False
3       False
4       False
        ...
1304     True
1305     True
1306    False
1307     True
1308     True
Length: 1309, dtype: bool

In [103]:
df.duplicated(subset="age",keep="last")

0        True
1        True
2        True
3        True
4        True
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Length: 1309, dtype: bool

In [104]:
import pandas as pd
import numpy as np

data={"id":[1,2,2,3,4],"Name":["Amit","Priya","Raj","Rahul","Priya"],"Marks":[80,35,75,85,65],"City":["Ahmedabad","Rajkot","Rajkot","Surat","Ahmedabad"]}
df=pd.DataFrame(data)
print(df)

   id   Name  Marks       City
0   1   Amit     80  Ahmedabad
1   2  Priya     35     Rajkot
2   2    Raj     75     Rajkot
3   3  Rahul     85      Surat
4   4  Priya     65  Ahmedabad

In [114]:
df.duplicated(subset="City")

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [112]:
df.duplicated(subset="City",keep="first")

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [111]:
df.duplicated(subset="City",keep="last")

0     True
1     True
2    False
3    False
4    False
dtype: bool